import type { Colaborador } from "./types";

// Base importada da planilha oficial "LISTAGEM DE COLABORADORES - GRUPOS LEMA".
const BASE = [
  {
    id: "col-1",
    nome: "John Wanderson Lima Couto",
    empresa_grupo: "LEMA",
    setor: "Financeiro",
    formato_trabalho: "presencial",
    email: "john@lemaef.com.br",
    data_aniversario: "2023-08-23",
    data_ingresso: "2023-01-11",
    tem_filhos: false,
    tamanho_farda: "M",
    genero: "Masculino",
    tipo_contratacao: "Estágiário(a) - 6h",
    curso_formacao: "Economia - andamento",
    detalhes_filhos: "",
    endereco: "Rua 32, Casa 325A, Jereissate 1, Maracanaú CE",
    contato_emergencia_parentesco: "Pai/Mãe",
    contato_emergencia_nome: "Afoncina Lima Cavalcante",
    contato_emergencia_telefone: "85988840797",
    restricao_alimentar: "",
    hobby: "Comer assistindo e treinar na academia",
    foto_url: "",
  },
  {
    id: "col-2",
    nome: "Matheus Crisóstomo Holanda",
    empresa_grupo: "LEMA",
    setor: "Técnico",
    formato_trabalho: "presencial",
    email: "matheus@lemaef.com.br",
    data_aniversario: "1995-02-22",
    data_ingresso: "2017-08-07",
    tem_filhos: true,
    tamanho_farda: "M",
    genero: "Masculino",
    tipo_contratacao: "Sócio(a)",
    curso_formacao: "Ciências Econômicas",
    detalhes_filhos: "Uma filha de dois anos",
    endereco: "Rua Lourdes Vidal Alves, 810, casa 02. 60831160",
    contato_emergencia_parentesco: "Esposo/Esposa",
    contato_emergencia_nome: "Luiziana Cavalcante Costa Fernandes Crisóstomo",
    contato_emergencia_telefone: "85 99144-9706",
    restricao_alimentar: "",
    hobby: "Sair para beber",
    foto_url: "",
  },
  {
    id: "col-3",
    nome: "Maria Ariadne Alves Pereira Maciel",
    empresa_grupo: "LEMA",
    setor: "Comercial",
    formato_trabalho: "presencial",
    email: "ariadne@lemaef.com.br",
    data_aniversario: "1999-07-14",
    data_ingresso: "2021-08-09",
    tem_filhos: false,
    tamanho_farda: "P Baby Look",
    genero: "Feminino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Graduada em Administração",
    detalhes_filhos: "",
    endereco: "Rua Farias Lemos, 800, Bl C, Apt 921, Messejana, CEP: 60841-455",
    contato_emergencia_parentesco: "Esposo/Esposa",
    contato_emergencia_nome: "Miquéias Dantas Franklin",
    contato_emergencia_telefone: "85 98547-3780",
    restricao_alimentar: "",
    hobby: "Assistir séries, sair para comer, ir para barzinho, tirar fotos de paisagens, viajar.",
    foto_url: "",
  },
  {
    id: "col-4",
    nome: "Isaías Pereira dos Santos",
    empresa_grupo: "LEMA",
    setor: "Tecnologia",
    formato_trabalho: "hibrido",
    email: "isaias@lemaef.com.br",
    data_aniversario: "1999-04-30",
    data_ingresso: "2022-05-20",
    tem_filhos: false,
    tamanho_farda: "G",
    genero: "Masculino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Graduação em Defesa Cibernética",
    detalhes_filhos: "",
    endereco: "Rua Luís Alves Maia, 197",
    contato_emergencia_parentesco: "Madrinha",
    contato_emergencia_nome: "Antonia Rebeca Fernandes Matias",
    contato_emergencia_telefone: "85 98883-4225",
    restricao_alimentar: "",
    hobby: "Ler, aprender algo novo",
    foto_url: "",
  },
  {
    id: "col-5",
    nome: "Wesley Matias da Silva",
    empresa_grupo: "LEMA",
    setor: "Operacional",
    formato_trabalho: "presencial",
    email: "wesley@lemaef.com.br",
    data_aniversario: "2024-01-26",
    data_ingresso: "2023-02-08",
    tem_filhos: false,
    tamanho_farda: "G",
    genero: "Masculino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Administração em andamento",
    detalhes_filhos: "",
    endereco: "Rua Maranguape, 603",
    contato_emergencia_parentesco: "Esposo/Esposa",
    contato_emergencia_nome: "Samily de Andrade Alves Matias",
    contato_emergencia_telefone: "85 98624-1446",
    restricao_alimentar: "",
    hobby: "Assistir filmes, séries e sair com esposa",
    foto_url: "",
  },
  {
    id: "col-6",
    nome: "Ádila Silva Amaro",
    empresa_grupo: "LEMA Edu",
    setor: "Administrativo",
    formato_trabalho: "presencial",
    email: "adila@lemaef.com.br",
    data_aniversario: "1997-10-04",
    data_ingresso: "2024-11-08",
    tem_filhos: false,
    tamanho_farda: "M",
    genero: "Feminino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Psicologia - Em andamento",
    detalhes_filhos: "",
    endereco: "Rua Coronel Luiz David de Souza, 102, apto 601B, Presidente Kennedy",
    contato_emergencia_parentesco: "Pai/Mãe",
    contato_emergencia_nome: "Pedro Sergio de Lima Amaro",
    contato_emergencia_telefone: "85985166044",
    restricao_alimentar: "",
    hobby:
      "Acampar, fazer trilha, ir para algum barzinho, ouvir música, tocar violão, ler um livro, estudar, cozinhar.",
    foto_url: "",
  },
  {
    id: "col-7",
    nome: "Antônio Sidrônio de Santana Neto",
    empresa_grupo: "LEMA",
    setor: "Técnico",
    formato_trabalho: "remoto",
    email: "antonio@lemaef.com.br",
    data_aniversario: "1991-04-23",
    data_ingresso: "2022-05-02",
    tem_filhos: false,
    tamanho_farda: "GG",
    genero: "Masculino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Ciências Atuariais",
    detalhes_filhos: "",
    endereco: "R. José Braz Moscow, 497 - Piedade, Jaboatão dos Guararapes - PE, 54410-390",
    contato_emergencia_parentesco: "Esposo/Esposa",
    contato_emergencia_nome: "Priscila Romão Caldas",
    contato_emergencia_telefone: "81983041371",
    restricao_alimentar: "",
    hobby: "Música, filme, literatura e café, muito café.",
    foto_url: "",
  },
  {
    id: "col-8",
    nome: "Antonio Állef Vieira de Sousa do Nascimento",
    empresa_grupo: "LEMA Edu",
    setor: "Comercial",
    formato_trabalho: "presencial",
    email: "allef@lemaef.com.br",
    data_aniversario: "1998-08-06",
    data_ingresso: "2023-04-03",
    tem_filhos: false,
    tamanho_farda: "M",
    genero: "Masculino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "S/I",
    detalhes_filhos: "",
    endereco: "Rua Damasceno Girão, 2113, 60410444. Jardim América",
    contato_emergencia_parentesco: "Esposo/Esposa",
    contato_emergencia_nome: "Mayara Karlla",
    contato_emergencia_telefone: "85 998426538",
    restricao_alimentar: "",
    hobby: "Jogar videogame 🎮",
    foto_url: "",
  },
  {
    id: "col-9",
    nome: "Bruna Araújo e Silva",
    empresa_grupo: "LEMA",
    setor: "Técnico",
    formato_trabalho: "remoto",
    email: "bruna@lemaef.com.br",
    data_aniversario: "1998-01-08",
    data_ingresso: "2022-03-03",
    tem_filhos: true,
    tamanho_farda: "P",
    genero: "Feminino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Ciências Econômicas - concluído em 2021.",
    detalhes_filhos: "1 filho - 7 meses",
    endereco: "Sítio Pilões s/n - Zona Rural, Ubajara-CE",
    contato_emergencia_parentesco: "Irmão/Irmã",
    contato_emergencia_nome: "Thalia Araújo e Silva",
    contato_emergencia_telefone: "88 994785272",
    restricao_alimentar: "",
    hobby: "Sair para comer; assistir filmes e séries.",
    foto_url: "",
  },
  {
    id: "col-10",
    nome: "Thalia Araújo e Silva",
    empresa_grupo: "LEMA",
    setor: "Operacional",
    formato_trabalho: "remoto",
    email: "thalia@lemaef.com.br",
    data_aniversario: "1999-12-30",
    data_ingresso: "2023-02-01",
    tem_filhos: true,
    tamanho_farda: "P",
    genero: "Feminino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Ciências Econômicas - Em andamento",
    detalhes_filhos: "1 filho, 2 anos",
    endereco: "Rua Padre Francisco Pinto, n 34, Monte Castelo, Ubajara-CE 62350-000",
    contato_emergencia_parentesco: "Esposo/Esposa",
    contato_emergencia_nome: "Jonathan Holanda Araújo",
    contato_emergencia_telefone: "88 98152-1523",
    restricao_alimentar: "",
    hobby: "Assistir série/filme; trabalhos manuais: crochê, costura, etc.",
    foto_url: "",
  },
  {
    id: "col-11",
    nome: "Felipe Mafuz Nogueira",
    empresa_grupo: "LEMA",
    setor: "Técnico",
    formato_trabalho: "presencial",
    email: "felipe@lemaef.com.br",
    data_aniversario: "1995-02-23",
    data_ingresso: "2023-04-03",
    tem_filhos: false,
    tamanho_farda: "M",
    genero: "Masculino",
    tipo_contratacao: "Efetivo",
    curso_formacao:
      "Ciências Econômicas - Em andamento;   Cinema e Audiovisual (comunicação) - Concluído",
    detalhes_filhos: "",
    endereco: "Rua Tibúrcio Cavalcante, 2593. Dionísio Torres, Fortaleza-CE",
    contato_emergencia_parentesco: "Pai/Mãe",
    contato_emergencia_nome: "Maristela do Rocio Belina Mafuz Nogueira",
    contato_emergencia_telefone: "(85) 99981-7411",
    restricao_alimentar: "",
    hobby: "Viajar, praticar esportes, ler, sair com amigos.",
    foto_url: "",
  },
  {
    id: "col-12",
    nome: "Gilmarqueson Pereira da Silva Júnior",
    empresa_grupo: "LEMA",
    setor: "Comercial",
    formato_trabalho: "hibrido",
    email: "gil@lemaef.com.br",
    data_aniversario: "1990-06-06",
    data_ingresso: "2024-01-08",
    tem_filhos: true,
    tamanho_farda: "G",
    genero: "Masculino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Administração",
    detalhes_filhos: "Uma",
    endereco: "Rua Constança, 675. 52.121-580",
    contato_emergencia_parentesco: "Pai/Mãe",
    contato_emergencia_nome: "Maria Angélica da Silva Nunes",
    contato_emergencia_telefone: "8199399-9479",
    restricao_alimentar: "",
    hobby: "Cozinhar, ler e malhar.",
    foto_url: "",
  },
  {
    id: "col-13",
    nome: "Ricardo da Silva Bringel",
    empresa_grupo: "LEMA",
    setor: "Financeiro",
    formato_trabalho: "presencial",
    email: "",
    data_aniversario: "1972-03-17",
    data_ingresso: "2022-07-15",
    tem_filhos: true,
    tamanho_farda: "M",
    genero: "Masculino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Não tenho nenhum curso",
    detalhes_filhos: "Tenho três filhos",
    endereco: "Rua Curitiba 1186. Autran Nunes",
    contato_emergencia_parentesco: "Esposo/Esposa",
    contato_emergencia_nome: "Antônia Lindalva da Silva Bringel",
    contato_emergencia_telefone: "85987671493",
    restricao_alimentar: "",
    hobby: "Para comer",
    foto_url: "",
  },
  {
    id: "col-14",
    nome: "Iago Montenegro Barbosa",
    empresa_grupo: "Hot New Code",
    setor: "Tecnologia",
    formato_trabalho: "remoto",
    email: "iago@hnwc.com.br",
    data_aniversario: "1993-04-12",
    data_ingresso: "2020-10-01",
    tem_filhos: false,
    tamanho_farda: "G",
    genero: "Masculino",
    tipo_contratacao: "Sócio(a)",
    curso_formacao: "Análise e desenvolvimento de sistemas - ADS",
    detalhes_filhos: "",
    endereco: "Rua Doutor Miguel Couto, 564, Paupina, Fortaleza/CE",
    contato_emergencia_parentesco: "Pai/Mãe",
    contato_emergencia_nome: "Regina Selma Gonçalves Montenegro",
    contato_emergencia_telefone: "85 999009335",
    restricao_alimentar: "",
    hobby: "Tocar guitarra, malhar, sair pra comer e tomar uma cervejinha",
    foto_url: "",
  },
  {
    id: "col-15",
    nome: "Vítor Leitão Rocha",
    empresa_grupo: "LEMA",
    setor: "Comercial",
    formato_trabalho: "presencial",
    email: "vitor@lemaef.com.br",
    data_aniversario: "1985-07-09",
    data_ingresso: "2011-12-01",
    tem_filhos: true,
    tamanho_farda: "M",
    genero: "Masculino",
    tipo_contratacao: "Sócio(a)",
    curso_formacao: "Economia",
    detalhes_filhos: "2, 11 e 6 anos",
    endereco: "Rua Doutor José Lino, 171, Ap. 2202 torre Miró, Mucuripe, Fortaleza/CE",
    contato_emergencia_parentesco: "Esposo/Esposa",
    contato_emergencia_nome: "Ana Karine Nogueira de Moura Rocha",
    contato_emergencia_telefone: "85 998200222",
    restricao_alimentar: "",
    hobby: "Família, viagem, barzinho",
    foto_url: "",
  },
  {
    id: "col-16",
    nome: "Gregório Pinto Matias",
    empresa_grupo: "LEMA",
    setor: "Financeiro",
    formato_trabalho: "presencial",
    email: "gregorio@lemaef.com.br",
    data_aniversario: "1985-04-29",
    data_ingresso: "2011-12-01",
    tem_filhos: true,
    tamanho_farda: "G",
    genero: "Masculino",
    tipo_contratacao: "Sócio(a)",
    curso_formacao: "Administração de Empresas",
    detalhes_filhos: "1 filho de 5 anos e uma filha de 12",
    endereco: "Dom Expedito Lopes, 2255, Ap 1703. 60135-410 Dionisio Torres, Fortaleza/CE",
    contato_emergencia_parentesco: "Pai/Mãe",
    contato_emergencia_nome: "Everardo Fernandes Matias",
    contato_emergencia_telefone: "85 99820-5678",
    restricao_alimentar: "",
    hobby: "Filmes, Leitura, Música, Bar e Restaurante e Silêncio",
    foto_url: "",
  },
  {
    id: "col-17",
    nome: "Rodolpho Matheus de Santana Malafaia",
    empresa_grupo: "LEMA",
    setor: "Comercial",
    formato_trabalho: "remoto",
    email: "rodolpho@lemaef.com.br",
    data_aniversario: "1990-07-17",
    data_ingresso: "2021-09-22",
    tem_filhos: false,
    tamanho_farda: "G",
    genero: "Masculino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Ciências Atuariais",
    detalhes_filhos: "",
    endereco:
      "Avenida Bernardo Vieira de Melo, 6436, apto 601. 54450-020. Candeias, Jaboatão dos Guararapes/PE",
    contato_emergencia_parentesco: "Esposo/Esposa",
    contato_emergencia_nome: "Taynara de Aguiar Rodrigues Malafaia",
    contato_emergencia_telefone: "81995377290",
    restricao_alimentar: "",
    hobby: "Praia para relaxar",
    foto_url: "",
  },
  {
    id: "col-18",
    nome: "Elison da Silva Costa",
    empresa_grupo: "LEMA Edu",
    setor: "Comercial",
    formato_trabalho: "presencial",
    email: "elison@lemaef.com.br",
    data_aniversario: "1998-12-15",
    data_ingresso: "2022-04-07",
    tem_filhos: false,
    tamanho_farda: "M",
    genero: "Masculino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "S/I",
    detalhes_filhos: "",
    endereco: "Rua Rodrigues de Andrade 422 - Apto 403",
    contato_emergencia_parentesco: "Pai/Mãe",
    contato_emergencia_nome: "Maria Elianir da Silva Costa",
    contato_emergencia_telefone: "+55 88 99405-9272",
    restricao_alimentar: "Alérgico a frutos do mar",
    hobby: "Treinar, ir à praia, ir a cafés, pedalar, viajar e sair com os amigos para rolês.",
    foto_url: "",
  },
  {
    id: "col-19",
    nome: "Vítor Hugo da Cruz Teobaldo",
    empresa_grupo: "LEMA",
    setor: "Comercial",
    formato_trabalho: "presencial",
    email: "vitorhugo@lemaef.com.br",
    data_aniversario: "2000-03-29",
    data_ingresso: "2024-01-19",
    tem_filhos: false,
    tamanho_farda: "M",
    genero: "Masculino",
    tipo_contratacao: "Efetivo",
    curso_formacao:
      "Administração - Concluída (Em 2023.2, Diploma à receber) | Sistemas de Informação - Em andamento.",
    detalhes_filhos: "",
    endereco: "Rua Edgard Augusto Teixeira, 1560, 61935-150, Boa Esperança. Maracanaú/CE",
    contato_emergencia_parentesco: "Pai/Mãe",
    contato_emergencia_nome: "Vladilson Teobaldo",
    contato_emergencia_telefone: "85 98805-0389",
    restricao_alimentar: "",
    hobby: "Praticar exercícios, jogar e sair para comer.",
    foto_url: "",
  },
  {
    id: "col-20",
    nome: "Bianca Luiza Araújo Gurgel do Amaral",
    empresa_grupo: "LEMA",
    setor: "Operacional",
    formato_trabalho: "presencial",
    email: "bianca@lemaef.com.br",
    data_aniversario: "2000-05-05",
    data_ingresso: "2024-02-05",
    tem_filhos: false,
    tamanho_farda: "G",
    genero: "Feminino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Administração - Em andamento",
    detalhes_filhos: "",
    endereco: "Rua Eder Aleixo, 302. 60875-580. São Bento, Fortaleza/CE.",
    contato_emergencia_parentesco: "Pai/Mãe",
    contato_emergencia_nome: "Ricado Luis Pinto Gurgel do Amaral",
    contato_emergencia_telefone: "85 9 8755-3556",
    restricao_alimentar: "",
    hobby: "Sair pra comer, cinema, assistir série.",
    foto_url: "",
  },
  {
    id: "col-21",
    nome: "Levi Bandeira Pessoa",
    empresa_grupo: "LEMA",
    setor: "Financeiro",
    formato_trabalho: "presencial",
    email: "levi@lemaef.com.br",
    data_aniversario: "1986-11-13",
    data_ingresso: "2018-09-03",
    tem_filhos: false,
    tamanho_farda: "G",
    genero: "Masculino",
    tipo_contratacao: "Sócio(a)",
    curso_formacao: "Administração",
    detalhes_filhos: "0",
    endereco: "Rua Zuca Accioly, 663 - apt 101B",
    contato_emergencia_parentesco: "Esposo/Esposa",
    contato_emergencia_nome: "Wládia Maria Coutinho Paixão Pessoa",
    contato_emergencia_telefone: "999870966",
    restricao_alimentar: "Intolerante à lactose",
    hobby: "Assistir Filmes, Séries, Sair para comer",
    foto_url: "",
  },
  {
    id: "col-22",
    nome: "Wallyson Queiróz Diógenes",
    empresa_grupo: "LEMA",
    setor: "Técnico",
    formato_trabalho: "presencial",
    email: "wallyson@lemaef.com.br",
    data_aniversario: "1993-10-22",
    data_ingresso: "2024-04-08",
    tem_filhos: false,
    tamanho_farda: "GG",
    genero: "Masculino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Comércio exterior/Finanças",
    detalhes_filhos: "",
    endereco: "Rua Dr Waldemar de Alcântara 1509, Sapiranga - ap201b",
    contato_emergencia_parentesco: "Pai/Mãe",
    contato_emergencia_nome: "José Diógenes",
    contato_emergencia_telefone: "88999670325",
    restricao_alimentar: "",
    hobby: "Cinema",
    foto_url: "",
  },
  {
    id: "col-23",
    nome: "Rodrigo Dias Guimarães",
    empresa_grupo: "LEMA",
    setor: "Operacional",
    formato_trabalho: "presencial",
    email: "rodrigo@lemaef.com.br",
    data_aniversario: "2000-08-15",
    data_ingresso: "2024-07-01",
    tem_filhos: false,
    tamanho_farda: "G",
    genero: "Masculino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Economia - Em andamento",
    detalhes_filhos: "",
    endereco: "Av Santos Dumont, 6915, apto 103",
    contato_emergencia_parentesco: "Pai/Mãe",
    contato_emergencia_nome: "Suyanne Andrade Dias",
    contato_emergencia_telefone: "85 988718906",
    restricao_alimentar: "Alérgico a frutos do mar",
    hobby: "Ouvir música, praticar esportes, ler, aprender instrumentos.",
    foto_url: "",
  },
  {
    id: "col-24",
    nome: "Maria Eduarda Benício de Queiroz",
    empresa_grupo: "LEMA",
    setor: "Operacional",
    formato_trabalho: "presencial",
    email: "eduarda@lemaef.com.br",
    data_aniversario: "2001-08-24",
    data_ingresso: "2024-07-01",
    tem_filhos: false,
    tamanho_farda: "PP",
    genero: "Feminino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Ciências Econômicas - Em andamento",
    detalhes_filhos: "",
    endereco: "Rua Grécia 90, Parangaba",
    contato_emergencia_parentesco: "Esposo/Esposa",
    contato_emergencia_nome: "João Jorge de Oliveira Feitosa Silva",
    contato_emergencia_telefone: "(85) 999574659",
    restricao_alimentar: "",
    hobby: "Assistir série, sair pra comer, ler",
    foto_url: "",
  },
  {
    id: "col-25",
    nome: "Levi Lima Brito Coelho",
    empresa_grupo: "LEMA",
    setor: "Financeiro",
    formato_trabalho: "presencial",
    email: "levicoelho@lemaef.com.br",
    data_aniversario: "2005-01-20",
    data_ingresso: "2024-08-19",
    tem_filhos: false,
    tamanho_farda: "P",
    genero: "Masculino",
    tipo_contratacao: "Estágiário(a) - 4h",
    curso_formacao: "Economia - Em andamento",
    detalhes_filhos: "",
    endereco: "Rua Clarindo Pereira, 1390. 60834-475. Edson Queiroz, Fortaleza/CE",
    contato_emergencia_parentesco: "Pai/Mãe",
    contato_emergencia_nome: "Francisca Giselle Lima Brito Coelho",
    contato_emergencia_telefone: "85 987552832",
    restricao_alimentar: "",
    hobby: "Assistir futebol e sair com amigos e família",
    foto_url: "",
  },
  {
    id: "col-26",
    nome: "Carlos Gustavo Leite Barbosa dos Santos",
    empresa_grupo: "LEMA",
    setor: "Comercial",
    formato_trabalho: "remoto",
    email: "gustavo@lemaef.com.br",
    data_aniversario: "1994-09-10",
    data_ingresso: "2018-01-01",
    tem_filhos: false,
    tamanho_farda: "G",
    genero: "Masculino",
    tipo_contratacao: "Sócio(a)",
    curso_formacao: "Administração",
    detalhes_filhos: "",
    endereco: "Rua Visconde de Nacar, 529, apt 297. 80.400-210. Mercês, Curitiba/PR.",
    contato_emergencia_parentesco: "Esposo/Esposa",
    contato_emergencia_nome: "Bianca Olímpio do Nascimento",
    contato_emergencia_telefone: "85989577837",
    restricao_alimentar: "",
    hobby: "Tomar uma e dançar forró.",
    foto_url: "",
  },
  {
    id: "col-27",
    nome: "Jérémy Mikaël Jean-François Lemercier",
    empresa_grupo: "Hot New Code",
    setor: "Tecnologia",
    formato_trabalho: "hibrido",
    email: "jeremy@lemaef.com.br",
    data_aniversario: "1995-06-13",
    data_ingresso: "2025-06-01",
    tem_filhos: false,
    tamanho_farda: "M",
    genero: "Masculino",
    tipo_contratacao: "PJ",
    curso_formacao: "Engenheiro da Computação",
    detalhes_filhos: "",
    endereco: "Rua Solón Pinheiro 1307. Bairro José Bonifácio. 60050-041. Fortaleza/CE",
    contato_emergencia_parentesco: "Esposo/Esposa",
    contato_emergencia_nome: "Rachel Lemos Lopes",
    contato_emergencia_telefone: "85 99964-8888",
    restricao_alimentar: "Intolerante à lactose",
    hobby: "Leitura, exercícios físicos e passeios",
    foto_url: "",
  },
  {
    id: "col-28",
    nome: "Davi Cipriano da Silva",
    empresa_grupo: "LEMA",
    setor: "Operacional",
    formato_trabalho: "presencial",
    email: "davi@lemaef.com.br",
    data_aniversario: "2002-12-01",
    data_ingresso: "2025-03-12",
    tem_filhos: false,
    tamanho_farda: "P",
    genero: "Masculino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Finanças - Em andamento",
    detalhes_filhos: "",
    endereco: "Rua Américo Rocha Lima,1023. Vila Manoel Sátiro",
    contato_emergencia_parentesco: "Pai/Mãe",
    contato_emergencia_nome: "Maria Sueli Cipriano da Silva",
    contato_emergencia_telefone: "85 98834-6446",
    restricao_alimentar: "",
    hobby:
      "Ler livros e notícias sobre a área de formação; assistir séries e filmes; jogar videogame; caminhar e pedalar; sair com os amigos e sair para comer",
    foto_url: "",
  },
  {
    id: "col-29",
    nome: "José Winston Freitas Costa",
    empresa_grupo: "LEMA",
    setor: "Operacional",
    formato_trabalho: "presencial",
    email: "winston@lemaef.com.br",
    data_aniversario: "2002-05-17",
    data_ingresso: "2025-07-10",
    tem_filhos: false,
    tamanho_farda: "PP",
    genero: "Masculino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Ciências Econômicas - Em andamento",
    detalhes_filhos: "",
    endereco: "Rua Bulgária, 926. 60713-500. Vila Manoel Sátiro, Fortaleza/CE",
    contato_emergencia_parentesco: "Pai/Mãe",
    contato_emergencia_nome: "Antonia Paula de Freitas",
    contato_emergencia_telefone: "85 99949-7529",
    restricao_alimentar: "",
    hobby:
      "Passear na beira-mar, penspinning, cardistry, puzzles, ler, jogar poker e brincar com minha afilhada.",
    foto_url: "",
  },
  {
    id: "col-30",
    nome: "Francisco Jefferson Privino de Oliveira",
    empresa_grupo: "LEMA",
    setor: "Marketing",
    formato_trabalho: "presencial",
    email: "jefferson@lemaef.com.br",
    data_aniversario: "1990-07-01",
    data_ingresso: "2025-07-30",
    tem_filhos: false,
    tamanho_farda: "G",
    genero: "Masculino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Jornalismo",
    detalhes_filhos: "",
    endereco: "Avenida Tenente Lisboa, 1544 - Jacarecanga - 60.310-240 - Fortaleza/CE",
    contato_emergencia_parentesco: "Esposo/Esposa",
    contato_emergencia_nome: "Débora da Silva Paula",
    contato_emergencia_telefone: "85987816900",
    restricao_alimentar: "Intolerante à lactose;",
    hobby:
      "Pratico corrida, academia, estou voltando ao ciclismo, sou ávido leitor de livros literários e de newsletters de marketing. Amo fazer cursos para continuar sempre aprendendo.",
    foto_url: "",
  },
  {
    id: "col-31",
    nome: "Alessandra Martins de Lima",
    empresa_grupo: "LEMA",
    setor: "Financeiro",
    formato_trabalho: "presencial",
    email: "alessandra@lemaef.com.br",
    data_aniversario: "1984-05-29",
    data_ingresso: "2025-09-25",
    tem_filhos: true,
    tamanho_farda: "P",
    genero: "Feminino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Administração - Em andamento",
    detalhes_filhos: "1 filha de 1 ano e 10 meses",
    endereco: "Rua 8 de Junho, 330, Casa C, Pici",
    contato_emergencia_parentesco: "Pai/Mãe",
    contato_emergencia_nome: "Maria Ivonilda Martins dos Santos",
    contato_emergencia_telefone: "85 98584-2314",
    restricao_alimentar: "",
    hobby: "Passear com minha filha",
    foto_url: "",
  },
  {
    id: "col-32",
    nome: "Murilo Lima de Moura",
    empresa_grupo: "LEMA",
    setor: "Técnico",
    formato_trabalho: "presencial",
    email: "murilo@lemaef.com.br",
    data_aniversario: "2004-01-17",
    data_ingresso: "2025-10-13",
    tem_filhos: false,
    tamanho_farda: "G",
    genero: "Masculino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Gestão Financeira - Concluído; Ciências Contábeis - Em andamento",
    detalhes_filhos: "",
    endereco: "Rua da Consolação, 263, 60.341-360. Aldeota, Fortaleza/CE",
    contato_emergencia_parentesco: "Pai/Mãe",
    contato_emergencia_nome: "Mayreanne Sobrinho Lima",
    contato_emergencia_telefone: "85992677658",
    restricao_alimentar: "",
    hobby: "Fazer qualquer tipo de esporte, conhecer novos restaurantes, praia.",
    foto_url: "",
  },
  {
    id: "col-33",
    nome: "Pedro Henrique Dias de Carvalho de Barros e Silva",
    empresa_grupo: "Numo",
    setor: "Tecnologia",
    formato_trabalho: "presencial",
    email: "pedrocarvalho@lemaef.com.br",
    data_aniversario: "2000-10-11",
    data_ingresso: "2025-11-18",
    tem_filhos: false,
    tamanho_farda: "G",
    genero: "Masculino",
    tipo_contratacao: "Estágiário(a) - 6h",
    curso_formacao: "Análise e Desenvolvimento de Sistemas",
    detalhes_filhos: "",
    endereco: "Rua J da Penha, 176",
    contato_emergencia_parentesco: "Namorada",
    contato_emergencia_nome: "Rafaela Chacur Alves Damasceno",
    contato_emergencia_telefone: "85 88673-103",
    restricao_alimentar: "",
    hobby: "Programar e Tocar bateria",
    foto_url: "",
  },
  {
    id: "col-34",
    nome: "Marcela Maria Silva",
    empresa_grupo: "LEMA",
    setor: "Comercial",
    formato_trabalho: "remoto",
    email: "marcela@lemaef.com.br",
    data_aniversario: "1990-12-27",
    data_ingresso: "",
    tem_filhos: false,
    tamanho_farda: "P",
    genero: "Feminino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Direito",
    detalhes_filhos: "",
    endereco: "Rua São José, 174, centro Angelim-PE",
    contato_emergencia_parentesco: "Pai/Mãe",
    contato_emergencia_nome: "Maria de Lourdes da Silva",
    contato_emergencia_telefone: "87 99195-1284",
    restricao_alimentar: "Intolerante à lactose",
    hobby: "Assistir séries, fazer trilha, camping.",
    foto_url: "",
  },
  {
    id: "col-35",
    nome: "Fernanda Fiorelli",
    empresa_grupo: "LEMA",
    setor: "Operacional",
    formato_trabalho: "remoto",
    email: "fernanda@lemaef.com.br",
    data_aniversario: "1988-12-17",
    data_ingresso: "",
    tem_filhos: true,
    tamanho_farda: "G",
    genero: "Feminino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Tecnólogo em logística - concluido - Administração ( em andamento)",
    detalhes_filhos: "1 filha- 07 anos",
    endereco: "Rua Nilo Peçanha, 1099- Centro- Birigui- São Paulo. CEP: 16.200-065",
    contato_emergencia_parentesco: "Esposo/Esposa",
    contato_emergencia_nome: "Daniel Leandro Boccardo",
    contato_emergencia_telefone: "18 99702-9014",
    restricao_alimentar: "",
    hobby: "Caminhadas, trekking, montanhismo",
    foto_url: "",
  },
  {
    id: "col-36",
    nome: "Gabriel Monteiro Fernandes",
    empresa_grupo: "LEMA",
    setor: "Tecnologia",
    formato_trabalho: "presencial",
    email: "gabrielfernandes@lemaef",
    data_aniversario: "1998-06-22",
    data_ingresso: "2025-11-18",
    tem_filhos: false,
    tamanho_farda: "G",
    genero: "Masculino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Análise e Desenvolvimento de Sistemas - Em andamento",
    detalhes_filhos: "",
    endereco: "Avenida Santos Dumont, 5600, ap 203b. 60192-018. Papicu, Fortaleza/CE",
    contato_emergencia_parentesco: "Pai/Mãe",
    contato_emergencia_nome: "Herbet Fernandes",
    contato_emergencia_telefone: "85 99146-1277",
    restricao_alimentar: "",
    hobby:
      "Música, tenho uma banda de pagode e tocamos aos finais de semana. Além disso, pratico vôlei de praia toda 3 vezes na semana",
    foto_url: "",
  },
  {
    id: "col-37",
    nome: "André Felipe Vianna de Brito Júnior",
    empresa_grupo: "LEMA",
    setor: "Marketing",
    formato_trabalho: "presencial",
    email: "andrefelipe@lemaef.com.br",
    data_aniversario: "1996-07-04",
    data_ingresso: "2026-05-07",
    tem_filhos: false,
    tamanho_farda: "G",
    genero: "Masculino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Designer Gráfico - Concluído",
    detalhes_filhos: "",
    endereco:
      "Avenida Maciel Bezerra, 132, Bloco 10, Apartamento 301. 60732-380. Siqueira, Maracanaú/CE",
    contato_emergencia_parentesco: "Esposo/Esposa",
    contato_emergencia_nome: "Izadora Vasconcelos Santana",
    contato_emergencia_telefone: "85 99943-4814",
    restricao_alimentar: "Intolerante à lactose",
    hobby: "Jogar video-game, sair para comer",
    foto_url: "",
  },
  {
    id: "col-38",
    nome: "Gabriel dos Santos Mendes",
    empresa_grupo: "LEMA Edu",
    setor: "Comercial",
    formato_trabalho: "presencial",
    email: "gabrielsantos@lemaef.com.br",
    data_aniversario: "1995-12-27",
    data_ingresso: "",
    tem_filhos: false,
    tamanho_farda: "G",
    genero: "Masculino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Direito",
    detalhes_filhos: "",
    endereco: "Rua 5, 100, condomínio solar das amoras",
    contato_emergencia_parentesco: "Pai/Mãe",
    contato_emergencia_nome: "Maria Lenira dos Santos",
    contato_emergencia_telefone: "85 99977-2752",
    restricao_alimentar: "Não tenho nenhuma restrição",
    hobby: "Assistir futebol, pegar uma praia, jogar beach tennis, sair com os amigos",
    foto_url: "",
  },
  {
    id: "col-39",
    nome: "Talita de Moura Alves",
    empresa_grupo: "LEMA",
    setor: "Comercial",
    formato_trabalho: "presencial",
    email: "talita@lemaef.com.br",
    data_aniversario: "1987-08-28",
    data_ingresso: "",
    tem_filhos: true,
    tamanho_farda: "G",
    genero: "Feminino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Direito",
    detalhes_filhos: "01 filha de 03 anos",
    endereco: "Av. Heráclito Graça, 733, apto 1904, Centro, Fortaleza-CE. CEP 60140-061",
    contato_emergencia_parentesco: "Esposo/Esposa",
    contato_emergencia_nome: "Ítalo Gomes de Melo",
    contato_emergencia_telefone: "68 999591602",
    restricao_alimentar: "",
    hobby: "Praia e piscina com a família. Barzinho com meu esposo.",
    foto_url: "",
  },
  {
    id: "col-40",
    nome: "Everton Igor Nobre dos Santos",
    empresa_grupo: "LEMA",
    setor: "Marketing",
    formato_trabalho: "presencial",
    email: "igor@lemaef.com.br",
    data_aniversario: "1995-08-05",
    data_ingresso: "2026-08-10",
    tem_filhos: false,
    tamanho_farda: "M",
    genero: "Masculino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Designer Gráfico",
    detalhes_filhos: "",
    endereco: "Rua Teodoreto Souto, 1005, ap. 5. 60430-730. Rodolfo Teófilo, Fortaleza/CE",
    contato_emergencia_parentesco: "Esposo/Esposa",
    contato_emergencia_nome: "Amanda de Lima Lessa",
    contato_emergencia_telefone: "85 99773-5454",
    restricao_alimentar: "",
    hobby: "Andar de bicicleta e ir para praia",
    foto_url: "",
  },
  {
    id: "col-41",
    nome: "Mykerlles Ferreira Farias",
    empresa_grupo: "LEMA",
    setor: "Financeiro",
    formato_trabalho: "presencial",
    email: "mykerlles@lemaef.com.br",
    data_aniversario: "1990-04-10",
    data_ingresso: "",
    tem_filhos: false,
    tamanho_farda: "M",
    genero: "Masculino",
    tipo_contratacao: "Efetivo",
    curso_formacao: "Administração e Gestao Financeira",
    detalhes_filhos: "",
    endereco: "Rua VII, 27, Conj 8 de Setembro. 40744-880.Fortaleza/Ceara",
    contato_emergencia_parentesco: "Irmão/Irmã",
    contato_emergencia_nome: "Walkerlles Ferreira Farias",
    contato_emergencia_telefone: "85 98568 9761",
    restricao_alimentar: "",
    hobby: "Família, viajar, treinar, comer, ler, praia",
    foto_url: "",
  },
] as const;

export function colaboradoresSeed(now: string): Colaborador[] {
  return BASE.map((c) => ({ ...c, created_at: now, updated_at: now }));
}
