/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as CastanhasRouteImport } from './routes/castanhas'
import { Route as ColaboradoresRouteImport } from './routes/colaboradores'
import { Route as EstoqueCanetasRouteImport } from './routes/estoque-canetas'
import { Route as EstoqueCoposRouteImport } from './routes/estoque-copos'
import { Route as EstoqueFardamentosRouteImport } from './routes/estoque-fardamentos'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as GastosEndomarketingRouteImport } from './routes/gastos-endomarketing'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PerfilRouteImport } from './routes/perfil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const CastanhasRoute = CastanhasRouteImport.update({
  id: '/castanhas',
  path: '/castanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradoresRoute = ColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueCanetasRoute = EstoqueCanetasRouteImport.update({
  id: '/estoque-canetas',
  path: '/estoque-canetas',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueCoposRoute = EstoqueCoposRouteImport.update({
  id: '/estoque-copos',
  path: '/estoque-copos',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueFardamentosRoute = EstoqueFardamentosRouteImport.update({
  id: '/estoque-fardamentos',
  path: '/estoque-fardamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosEndomarketingRoute = GastosEndomarketingRouteImport.update({
  id: '/gastos-endomarketing',
  path: '/gastos-endomarketing',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alertas': typeof AlertasRoute
  '/castanhas': typeof CastanhasRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/estoque-canetas': typeof EstoqueCanetasRoute
  '/estoque-copos': typeof EstoqueCoposRoute
  '/estoque-fardamentos': typeof EstoqueFardamentosRoute
  '/eventos': typeof EventosRoute
  '/financeiro': typeof FinanceiroRoute
  '/gastos-endomarketing': typeof GastosEndomarketingRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alertas': typeof AlertasRoute
  '/castanhas': typeof CastanhasRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/estoque-canetas': typeof EstoqueCanetasRoute
  '/estoque-copos': typeof EstoqueCoposRoute
  '/estoque-fardamentos': typeof EstoqueFardamentosRoute
  '/eventos': typeof EventosRoute
  '/financeiro': typeof FinanceiroRoute
  '/gastos-endomarketing': typeof GastosEndomarketingRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alertas': typeof AlertasRoute
  '/castanhas': typeof CastanhasRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/estoque-canetas': typeof EstoqueCanetasRoute
  '/estoque-copos': typeof EstoqueCoposRoute
  '/estoque-fardamentos': typeof EstoqueFardamentosRoute
  '/eventos': typeof EventosRoute
  '/financeiro': typeof FinanceiroRoute
  '/gastos-endomarketing': typeof GastosEndomarketingRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alertas'
    | '/castanhas'
    | '/colaboradores'
    | '/estoque-canetas'
    | '/estoque-copos'
    | '/estoque-fardamentos'
    | '/eventos'
    | '/financeiro'
    | '/gastos-endomarketing'
    | '/historico'
    | '/login'
    | '/perfil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alertas'
    | '/castanhas'
    | '/colaboradores'
    | '/estoque-canetas'
    | '/estoque-copos'
    | '/estoque-fardamentos'
    | '/eventos'
    | '/financeiro'
    | '/gastos-endomarketing'
    | '/historico'
    | '/login'
    | '/perfil'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alertas'
    | '/castanhas'
    | '/colaboradores'
    | '/estoque-canetas'
    | '/estoque-copos'
    | '/estoque-fardamentos'
    | '/eventos'
    | '/financeiro'
    | '/gastos-endomarketing'
    | '/historico'
    | '/login'
    | '/perfil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlertasRoute: typeof AlertasRoute
  CastanhasRoute: typeof CastanhasRoute
  ColaboradoresRoute: typeof ColaboradoresRoute
  EstoqueCanetasRoute: typeof EstoqueCanetasRoute
  EstoqueCoposRoute: typeof EstoqueCoposRoute
  EstoqueFardamentosRoute: typeof EstoqueFardamentosRoute
  EventosRoute: typeof EventosRoute
  FinanceiroRoute: typeof FinanceiroRoute
  GastosEndomarketingRoute: typeof GastosEndomarketingRoute
  HistoricoRoute: typeof HistoricoRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/castanhas': {
      id: '/castanhas'
      path: '/castanhas'
      fullPath: '/castanhas'
      preLoaderRoute: typeof CastanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaboradores': {
      id: '/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof ColaboradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque-canetas': {
      id: '/estoque-canetas'
      path: '/estoque-canetas'
      fullPath: '/estoque-canetas'
      preLoaderRoute: typeof EstoqueCanetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque-copos': {
      id: '/estoque-copos'
      path: '/estoque-copos'
      fullPath: '/estoque-copos'
      preLoaderRoute: typeof EstoqueCoposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque-fardamentos': {
      id: '/estoque-fardamentos'
      path: '/estoque-fardamentos'
      fullPath: '/estoque-fardamentos'
      preLoaderRoute: typeof EstoqueFardamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos-endomarketing': {
      id: '/gastos-endomarketing'
      path: '/gastos-endomarketing'
      fullPath: '/gastos-endomarketing'
      preLoaderRoute: typeof GastosEndomarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlertasRoute: AlertasRoute,
  CastanhasRoute: CastanhasRoute,
  ColaboradoresRoute: ColaboradoresRoute,
  EstoqueCanetasRoute: EstoqueCanetasRoute,
  EstoqueCoposRoute: EstoqueCoposRoute,
  EstoqueFardamentosRoute: EstoqueFardamentosRoute,
  EventosRoute: EventosRoute,
  FinanceiroRoute: FinanceiroRoute,
  GastosEndomarketingRoute: GastosEndomarketingRoute,
  HistoricoRoute: HistoricoRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
